# 国外节点使用
# 一致性构建镜像 buildah bud --no-cache -f Dockerfile-cn -t aspnmy/aspnmy_registry:cache-cn
FROM registry:latest

ADD htpasswd/aspnmy_registry.htpasswd /etc/docker/registry/aspnmy_registry.htpasswd
ADD cn/*.pem /certs/

# 配置缓存代理模式
ADD cn/*.yml /etc/docker/registry/config.yml


EXPOSE 5000

CMD ["/entrypoint.sh"]