# 国外节点使用
# 一致性构建镜像 buildah bud --no-cache -f Dockerfile-en -t aspnmy/aspnmy_registry:cache-en
FROM registry:2

ADD htpasswd/aspnmy_registry.htpasswd /etc/docker/registry/aspnmy_registry.htpasswd
ADD en/*.pem /certs/

# 配置缓存代理模式
ADD en/*.yml /etc/docker/registry/config.yml


EXPOSE 5000

CMD ["/entrypoint.sh"]